services:
    pim_volume_monitoring.volume.repository.aggregated_volume:
        class:  Pim\Bundle\CatalogVolumeMonitoringBundle\Persistence\Repository\Sql\AggregatedVolumeRepository
        arguments:
            - '@database_connection'
